import type { ChapterDef } from '../types'

export const chapters: ChapterDef[] = [

  // ── 1. Splitting ─────────────────────────────────────────────────────────
  {
    id: 1,
    title: 'Splitting',
    concept: 'Split one belt into equal portions',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 200 }, rate: 60 },
        narration: 'Start with one input belt at 60 items/min.', durationMs: 1500 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 280, y: 200 } },
        narration: 'A Splitter divides its input evenly across all connected outputs.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 500, y: 120 }, targetRate: 30 },
        narration: 'Place an output that wants 30/min.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-2', position: { x: 500, y: 280 }, targetRate: 30 },
        narration: 'And another output that wants 30/min.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-s1', targetHandle: 'in' },
        narration: 'Wire the input into the Splitter.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'd-out-1', sourceHandle: 'out-0' },
        narration: 'Connect one Splitter port to the first output.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'd-out-2', sourceHandle: 'out-1' },
        narration: '60 ÷ 2 connected ports = 30/min on each. Even split achieved.', durationMs: 2000 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 60, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 20, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 20, position: { x: 500, y: 200 } },
        { id: 'out-3', targetRate: 20, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 1, mergers: 0 },
      solution: {
        nodes: [{ id: 'sol-s1', type: 'splitterNode', position: { x: 280, y: 200 } }],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'out-3', sourceHandle: 'out-2' },
        ],
      },
    },
  },

  // ── 2. Merging ───────────────────────────────────────────────────────────
  {
    id: 2,
    title: 'Merging',
    concept: 'Combine belts; input rate must not exceed output belt capacity',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 140 }, rate: 60 },
        narration: 'Two input belts each carry 60/min.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-2', position: { x: 80, y: 280 }, rate: 60 },
        narration: 'They need to feed a single downstream machine.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 280, y: 220 } },
        narration: 'A Merger sums all of its inputs into one output.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 500, y: 220 }, targetRate: 120 },
        narration: 'The output needs 120/min — exactly 60 + 60.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-m1', targetHandle: 'in-0' },
        narration: 'Wire the first input into the Merger.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-in-2', target: 'd-m1', targetHandle: 'in-1' },
        narration: 'Wire the second input into a different Merger port.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-m1', target: 'd-out-1', sourceHandle: 'out' },
        narration: 'Watch the belt mark — its capacity must cover the merged total.', durationMs: 2000 },
    ],
    tryItPuzzle: {
      inputs: [
        { id: 'in-1', rate: 60, position: { x: 80, y: 160 } },
        { id: 'in-2', rate: 60, position: { x: 80, y: 280 } },
      ],
      outputs: [{ id: 'out-1', targetRate: 120, position: { x: 500, y: 220 } }],
      nodeBudget: { splitters: 0, mergers: 1 },
      solution: {
        nodes: [{ id: 'sol-m1', type: 'mergerNode', position: { x: 280, y: 220 } }],
        edges: [
          { source: 'in-1', target: 'sol-m1', targetHandle: 'in-0' },
          { source: 'in-2', target: 'sol-m1', targetHandle: 'in-1' },
          { source: 'sol-m1', target: 'out-1', sourceHandle: 'out' },
        ],
      },
    },
  },

  // ── 3. Lowest common denominator ─────────────────────────────────────────
  {
    id: 3,
    title: 'Lowest common denominator',
    concept: 'Reduce any ratio to a 1:N split',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 200 }, rate: 180 },
        narration: '180/min comes in on a single belt.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 280, y: 200 } },
        narration: 'Three machines downstream each need 60/min.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 500, y: 120 }, targetRate: 60 },
        narration: 'The GCD of {60, 60, 60} and 180 tells us 180 ÷ 3 = 60.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-2', position: { x: 500, y: 200 }, targetRate: 60 },
        narration: 'So we just need a 1:3 split — one Splitter is enough.', durationMs: 1500 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-3', position: { x: 500, y: 280 }, targetRate: 60 },
        narration: '', durationMs: 600 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-s1', targetHandle: 'in' },
        narration: 'Wire the input into the Splitter.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'd-out-1', sourceHandle: 'out-0' },
        narration: 'Each port carries 180 ÷ 3 = 60/min.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'd-out-2', sourceHandle: 'out-1' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s1', target: 'd-out-3', sourceHandle: 'out-2' },
        narration: 'Reducing the ratio first turns a hard problem into one Splitter.', durationMs: 2000 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 540, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 180, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 180, position: { x: 500, y: 200 } },
        { id: 'out-3', targetRate: 180, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 1, mergers: 0 },
      solution: {
        nodes: [{ id: 'sol-s1', type: 'splitterNode', position: { x: 280, y: 200 } }],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'out-3', sourceHandle: 'out-2' },
        ],
      },
    },
  },

  // ── 4. Combining concepts ────────────────────────────────────────────────
  {
    id: 4,
    title: 'Combining concepts',
    concept: 'Mix splits and merges to hit uneven targets',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 200 }, rate: 60 },
        narration: '60/min in, but the targets are uneven: 45 and 15.', durationMs: 1500 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 240, y: 200 } },
        narration: 'Step one: split 60 into two 30s.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s2', position: { x: 380, y: 280 } },
        narration: 'Step two: split one 30 into two 15s.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 460, y: 140 } },
        narration: 'Step three: merge 30 + 15 to make 45.', durationMs: 1500 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 600, y: 140 }, targetRate: 45 },
        narration: '', durationMs: 600 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-2', position: { x: 600, y: 320 }, targetRate: 15 },
        narration: 'The leftover 15 goes straight to the smaller output.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-s1', targetHandle: 'in' },
        narration: 'Splits and merges chain together to hit any ratio.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'd-m1', sourceHandle: 'out-0', targetHandle: 'in-0' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'd-s2', sourceHandle: 'out-1', targetHandle: 'in' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s2', target: 'd-m1', sourceHandle: 'out-0', targetHandle: 'in-1' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e5', source: 'd-s2', target: 'd-out-2', sourceHandle: 'out-1' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e6', source: 'd-m1', target: 'd-out-1', sourceHandle: 'out' },
        narration: 'Result: 60 → {45, 15} using 2 splitters and 1 merger.', durationMs: 2000 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 120, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 20, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 40, position: { x: 500, y: 200 } },
        { id: 'out-3', targetRate: 60, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 2, mergers: 1 },
      solution: {
        nodes: [
          { id: 'sol-s1', type: 'splitterNode', position: { x: 220, y: 200 } },
          { id: 'sol-s2', type: 'splitterNode', position: { x: 360, y: 280 } },
          { id: 'sol-m1', type: 'mergerNode',   position: { x: 360, y: 200 } },
        ],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-3', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'sol-m1', sourceHandle: 'out-1', targetHandle: 'in-0' },
          { source: 'sol-s1', target: 'sol-s2', sourceHandle: 'out-2', targetHandle: 'in' },
          { source: 'sol-s2', target: 'sol-m1', sourceHandle: 'out-0', targetHandle: 'in-1' },
          { source: 'sol-s2', target: 'out-1',  sourceHandle: 'out-1' },
          { source: 'sol-m1', target: 'out-2',  sourceHandle: 'out' },
        ],
      },
    },
  },

  // ── 5. Equal distribution ────────────────────────────────────────────────
  {
    id: 5,
    title: 'Equal distribution',
    concept: 'Balance multiple inputs into equal outputs',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 100 }, rate: 30 },
        narration: 'Three input belts at different rates: 30, 60, 90.', durationMs: 1400 },
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-2', position: { x: 80, y: 220 }, rate: 60 },
        narration: '', durationMs: 600 },
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-3', position: { x: 80, y: 340 }, rate: 90 },
        narration: '', durationMs: 600 },
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 240, y: 220 } },
        narration: 'Merge them all into a single 180/min belt.', durationMs: 1700 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 400, y: 220 } },
        narration: 'Now split that pool evenly into three 60/min outputs.', durationMs: 1700 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 580, y: 100 }, targetRate: 60 },
        narration: '', durationMs: 500 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-2', position: { x: 580, y: 220 }, targetRate: 60 },
        narration: '', durationMs: 500 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-3', position: { x: 580, y: 340 }, targetRate: 60 },
        narration: 'Pool first, then divide — uneven inputs, even outputs.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-m1', targetHandle: 'in-0' },
        narration: '', durationMs: 500 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-in-2', target: 'd-m1', targetHandle: 'in-1' },
        narration: '', durationMs: 500 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-in-3', target: 'd-m1', targetHandle: 'in-2' },
        narration: '', durationMs: 500 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-m1', target: 'd-s1', sourceHandle: 'out', targetHandle: 'in' },
        narration: 'Merger total: 30 + 60 + 90 = 180/min.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e5', source: 'd-s1', target: 'd-out-1', sourceHandle: 'out-0' },
        narration: '', durationMs: 500 },
      { action: { type: 'drawEdge', id: 'd-e6', source: 'd-s1', target: 'd-out-2', sourceHandle: 'out-1' },
        narration: '', durationMs: 500 },
      { action: { type: 'drawEdge', id: 'd-e7', source: 'd-s1', target: 'd-out-3', sourceHandle: 'out-2' },
        narration: 'Each output gets exactly 60/min — perfectly balanced.', durationMs: 2000 },
    ],
    tryItPuzzle: {
      inputs: [
        { id: 'in-1', rate: 20, position: { x: 80, y: 120 } },
        { id: 'in-2', rate: 40, position: { x: 80, y: 220 } },
        { id: 'in-3', rate: 60, position: { x: 80, y: 320 } },
      ],
      outputs: [
        { id: 'out-1', targetRate: 30, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 30, position: { x: 500, y: 220 } },
        { id: 'out-3', targetRate: 30, position: { x: 500, y: 320 } },
        { id: 'out-4', targetRate: 30, position: { x: 500, y: 420 } },
      ],
      nodeBudget: { splitters: 2, mergers: 3 },
      solution: {
        nodes: [
          { id: 'sol-m1', type: 'mergerNode',   position: { x: 220, y: 220 } },
          { id: 'sol-s1', type: 'splitterNode', position: { x: 360, y: 160 } },
          { id: 'sol-s2', type: 'splitterNode', position: { x: 360, y: 360 } },
          { id: 'sol-m2', type: 'mergerNode',   position: { x: 220, y: 360 } },
          { id: 'sol-m3', type: 'mergerNode',   position: { x: 220, y: 100 } },
        ],
        edges: [
          { source: 'in-1', target: 'sol-m1', targetHandle: 'in-0' },
          { source: 'in-2', target: 'sol-m1', targetHandle: 'in-1' },
          { source: 'in-3', target: 'sol-m1', targetHandle: 'in-2' },
          { source: 'sol-m1', target: 'sol-s1', sourceHandle: 'out', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'sol-s2', sourceHandle: 'out-2', targetHandle: 'in' },
          { source: 'sol-s2', target: 'out-3', sourceHandle: 'out-0' },
          { source: 'sol-s2', target: 'out-4', sourceHandle: 'out-1' },
        ],
      },
    },
  },

  // ── 6. Belt speed as a tool ──────────────────────────────────────────────
  {
    id: 6,
    title: 'Belt speed as a tool',
    concept: 'Higher-tier belts bypass split math',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 200 }, rate: 150 },
        narration: '150/min in. Targets: 60 and 90.', durationMs: 1500 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 280, y: 200 } },
        narration: 'A naive 1:2 split gives 75 + 75 — wrong ratio.', durationMs: 1700 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 500, y: 120 }, targetRate: 60 },
        narration: 'But belt capacities can throttle individual edges.', durationMs: 1700 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-2', position: { x: 500, y: 280 }, targetRate: 90 },
        narration: '', durationMs: 500 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-s1', targetHandle: 'in' },
        narration: 'Wire the input.', durationMs: 1200 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'd-out-1', sourceHandle: 'out-0', mark: 1 },
        narration: 'Top edge: Mk.1 belt → max 60/min.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'd-out-2', sourceHandle: 'out-1', mark: 2 },
        narration: 'Bottom edge: Mk.2 belt → max 120/min, takes 90.', durationMs: 1500 },
      { action: { type: 'pause' },
        narration: 'Belt tiers let you bias an even split into uneven flows.', durationMs: 2200 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 150, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 60, position: { x: 500, y: 150 } },
        { id: 'out-2', targetRate: 90, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 1, mergers: 0 },
      solution: {
        nodes: [{ id: 'sol-s1', type: 'splitterNode', position: { x: 280, y: 200 } }],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
        ],
      },
    },
  },

  // ── 7. Loopbacks ─────────────────────────────────────────────────────────
  {
    id: 7,
    title: 'Loopbacks',
    concept: 'Route excess belt back to build unbuildable ratios',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'inputNode', id: 'd-in-1', position: { x: 80, y: 220 }, rate: 60 },
        narration: '60/min in. Imagine five outputs each needing 12/min.', durationMs: 1500 },
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 220, y: 220 } },
        narration: 'A direct 1:5 split is impossible — splitters only divide by 2 or 3.', durationMs: 1900 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 360, y: 220 } },
        narration: 'Trick: feed a Merger that loops part of the output back into itself.', durationMs: 1900 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-1', position: { x: 560, y: 140 }, targetRate: 30 },
        narration: 'For now, watch a smaller version: input 60 looped to make a 1:3 splitter act 4-way.', durationMs: 1700 },
      { action: { type: 'placeNode', nodeType: 'outputNode', id: 'd-out-2', position: { x: 560, y: 320 }, targetRate: 30 },
        narration: '', durationMs: 400 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'd-in-1', target: 'd-m1', targetHandle: 'in-0' },
        narration: 'Input feeds the Merger.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-m1', target: 'd-s1', sourceHandle: 'out', targetHandle: 'in' },
        narration: 'Merger feeds the Splitter.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'd-out-1', sourceHandle: 'out-0' },
        narration: 'Two splitter ports go to outputs.', durationMs: 1200 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s1', target: 'd-out-2', sourceHandle: 'out-1' },
        narration: '', durationMs: 600 },
      { action: { type: 'drawEdge', id: 'd-e5', source: 'd-s1', target: 'd-m1', sourceHandle: 'out-2', targetHandle: 'in-1' },
        narration: 'The third loops back. The system self-balances; chain splitters to scale to 5+ ways.', durationMs: 2400 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 60, position: { x: 80, y: 220 } }],
      outputs: [
        { id: 'out-1', targetRate: 12, position: { x: 560, y: 80 } },
        { id: 'out-2', targetRate: 12, position: { x: 560, y: 160 } },
        { id: 'out-3', targetRate: 12, position: { x: 560, y: 240 } },
        { id: 'out-4', targetRate: 12, position: { x: 560, y: 320 } },
        { id: 'out-5', targetRate: 12, position: { x: 560, y: 400 } },
      ],
      nodeBudget: { splitters: 1, mergers: 1 },
      solution: {
        nodes: [
          { id: 'sol-m1', type: 'mergerNode',   position: { x: 220, y: 240 } },
          { id: 'sol-s1', type: 'splitterNode', position: { x: 360, y: 240 } },
        ],
        edges: [
          { source: 'in-1', target: 'sol-m1', targetHandle: 'in-0' },
          { source: 'sol-s1', target: 'sol-m1', sourceHandle: 'out-2', targetHandle: 'in-1' },
          { source: 'sol-m1', target: 'sol-s1', sourceHandle: 'out', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'out-3', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-4', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'out-5', sourceHandle: 'out-0' },
        ],
      },
    },
  },
]
