import type { ChapterDef } from '../types'

export const chapters: ChapterDef[] = [

  // ── 1. Splitting ─────────────────────────────────────────────────────────
  {
    id: 1,
    title: 'Splitting',
    concept: 'Split one belt into equal portions',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 280, y: 200 } },
        narration: 'A Splitter divides its input evenly across all connected ports.', durationMs: 1800 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-s1', targetHandle: 'in' },
        narration: 'Wire the input into the Splitter.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'out-1', sourceHandle: 'out-0' },
        narration: 'Connect the first port to an output.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'out-2', sourceHandle: 'out-1' },
        narration: 'Then the second port.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s1', target: 'out-3', sourceHandle: 'out-2' },
        narration: '60 ÷ 3 connected ports = 20/min on each. Even split achieved.', durationMs: 2200 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 60, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 20, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 20, position: { x: 500, y: 200 } },
        { id: 'out-3', targetRate: 20, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 1, mergers: 0 },
      solution: {
        nodes: [{ id: 'sol-s1', type: 'splitterNode', position: { x: 280, y: 200 } }],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in' },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'out-3', sourceHandle: 'out-2' },
        ],
      },
    },
  },

  // ── 2. Merging ───────────────────────────────────────────────────────────
  {
    id: 2,
    title: 'Merging',
    concept: 'Combine belts; pick a belt tier that fits the merged total',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 280, y: 220 } },
        narration: 'A Merger sums all of its inputs into one output.', durationMs: 1800 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-m1', targetHandle: 'in-0' },
        narration: 'Wire the first input into the Merger.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'in-2', target: 'd-m1', targetHandle: 'in-1' },
        narration: 'Wire the second input into a different Merger port.', durationMs: 1400 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-m1', target: 'out-1', sourceHandle: 'out', mark: 1 },
        narration: 'Wire the Merger to the output. But Mk.1 belts only carry 60/min — this edge wants 120, so it is overloaded (red).', durationMs: 2400 },
      { action: { type: 'setBeltMark', edgeId: 'd-e3', mark: 2 },
        narration: 'Belts come in tiers. Upgrading to a Mk.2 belt doubles the throughput to 120/min — exactly what we need.', durationMs: 2600 },
    ],
    tryItPuzzle: {
      inputs: [
        { id: 'in-1', rate: 60, position: { x: 80, y: 160 } },
        { id: 'in-2', rate: 60, position: { x: 80, y: 280 } },
      ],
      outputs: [{ id: 'out-1', targetRate: 120, position: { x: 500, y: 220 } }],
      nodeBudget: { splitters: 0, mergers: 1 },
      solution: {
        nodes: [{ id: 'sol-m1', type: 'mergerNode', position: { x: 280, y: 220 } }],
        edges: [
          { source: 'in-1', target: 'sol-m1', targetHandle: 'in-0' },
          { source: 'in-2', target: 'sol-m1', targetHandle: 'in-1' },
          { source: 'sol-m1', target: 'out-1', sourceHandle: 'out', mark: 2 },
        ],
      },
    },
  },

  // ── 3. Lowest common denominator ─────────────────────────────────────────
  {
    id: 3,
    title: 'Lowest common denominator',
    concept: 'Reduce any ratio to a 1:N split',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 280, y: 200 } },
        narration: '540/min in, three outputs at 180/min. GCD of those is 180 — so 540 ÷ 3 = 180.', durationMs: 2000 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-s1', targetHandle: 'in', mark: 5 },
        narration: 'Wire the input. The trunk needs a Mk.5 belt (780/min cap) to carry 540.', durationMs: 1800 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'out-1', sourceHandle: 'out-0', mark: 3 },
        narration: 'Each port carries 180/min — Mk.3 belts (270/min cap) handle that.', durationMs: 1800 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'out-2', sourceHandle: 'out-1', mark: 3 },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s1', target: 'out-3', sourceHandle: 'out-2', mark: 3 },
        narration: 'Reducing the ratio first turns a hard problem into one Splitter.', durationMs: 2000 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 540, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 180, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 180, position: { x: 500, y: 200 } },
        { id: 'out-3', targetRate: 180, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 1, mergers: 0 },
      solution: {
        nodes: [{ id: 'sol-s1', type: 'splitterNode', position: { x: 280, y: 200 } }],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in', mark: 5 },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0', mark: 3 },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1', mark: 3 },
          { source: 'sol-s1', target: 'out-3', sourceHandle: 'out-2', mark: 3 },
        ],
      },
    },
  },

  // ── 4. Combining concepts ────────────────────────────────────────────────
  {
    id: 4,
    title: 'Combining concepts',
    concept: 'Mix splits and merges to hit uneven targets',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 220, y: 200 } },
        narration: '120/min in, targets 20/40/60. Ratio 1:2:3 — sixths of 120 are 20s.', durationMs: 1900 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s2', position: { x: 360, y: 280 } },
        narration: 'Split 120 into thirds (40 each), then split one of those again into two 20s.', durationMs: 1900 },
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 360, y: 160 } },
        narration: 'A Merger combines a 40 with a 20 to make 60.', durationMs: 1700 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-s1', targetHandle: 'in', mark: 2 },
        narration: 'Trunk in: 120 needs a Mk.2 belt.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'd-m1', sourceHandle: 'out-0', targetHandle: 'in-0' },
        narration: 'First port (40) feeds the Merger.', durationMs: 1100 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'out-2', sourceHandle: 'out-1' },
        narration: 'Second port goes straight to the 40 output.', durationMs: 1100 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s1', target: 'd-s2', sourceHandle: 'out-2', targetHandle: 'in' },
        narration: 'Third port feeds the second Splitter.', durationMs: 1100 },
      { action: { type: 'drawEdge', id: 'd-e5', source: 'd-s2', target: 'd-m1', sourceHandle: 'out-0', targetHandle: 'in-1' },
        narration: 'One 20 joins the 40 in the Merger → 60.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e6', source: 'd-s2', target: 'out-1', sourceHandle: 'out-1' },
        narration: 'The other 20 satisfies the 20 output.', durationMs: 1100 },
      { action: { type: 'drawEdge', id: 'd-e7', source: 'd-m1', target: 'out-3', sourceHandle: 'out' },
        narration: 'Merger 60 satisfies the 60 output. Splits and merges chain to hit any ratio.', durationMs: 2200 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 120, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 20, position: { x: 500, y: 120 } },
        { id: 'out-2', targetRate: 40, position: { x: 500, y: 200 } },
        { id: 'out-3', targetRate: 60, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 2, mergers: 1 },
      solution: {
        nodes: [
          { id: 'sol-s1', type: 'splitterNode', position: { x: 220, y: 200 } },
          { id: 'sol-s2', type: 'splitterNode', position: { x: 360, y: 280 } },
          { id: 'sol-m1', type: 'mergerNode',   position: { x: 360, y: 160 } },
        ],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in', mark: 2 },
          { source: 'sol-s1', target: 'sol-m1', sourceHandle: 'out-0', targetHandle: 'in-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'sol-s2', sourceHandle: 'out-2', targetHandle: 'in' },
          { source: 'sol-s2', target: 'sol-m1', sourceHandle: 'out-0', targetHandle: 'in-1' },
          { source: 'sol-s2', target: 'out-1',  sourceHandle: 'out-1' },
          { source: 'sol-m1', target: 'out-3',  sourceHandle: 'out' },
        ],
      },
    },
  },

  // ── 5. Equal distribution ────────────────────────────────────────────────
  {
    id: 5,
    title: 'Equal distribution',
    concept: 'Pool uneven inputs, then divide them evenly',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 220, y: 220 } },
        narration: 'Three uneven inputs: 20, 40, 60. Merge them into one pool.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 360, y: 220 } },
        narration: 'Then split that 120/min pool evenly into the four outputs.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s2', position: { x: 500, y: 320 } },
        narration: 'Four outputs need a 1:4 split — one Splitter alone only does 1:3, so chain a second.', durationMs: 2000 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-m1', targetHandle: 'in-0' },
        narration: 'Wire all three inputs into the Merger.', durationMs: 1100 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'in-2', target: 'd-m1', targetHandle: 'in-1' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'in-3', target: 'd-m1', targetHandle: 'in-2' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-m1', target: 'd-s1', sourceHandle: 'out', targetHandle: 'in', mark: 2 },
        narration: 'Merged total 20+40+60 = 120 — needs a Mk.2 belt.', durationMs: 1700 },
      { action: { type: 'drawEdge', id: 'd-e5', source: 'd-s1', target: 'out-1', sourceHandle: 'out-0' },
        narration: 'First two outputs come straight off the Splitter.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e6', source: 'd-s1', target: 'out-2', sourceHandle: 'out-1' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e7', source: 'd-s1', target: 'd-s2', sourceHandle: 'out-2', targetHandle: 'in' },
        narration: 'The third port feeds another Splitter.', durationMs: 1100 },
      { action: { type: 'drawEdge', id: 'd-e8', source: 'd-s2', target: 'out-3', sourceHandle: 'out-0' },
        narration: 'Two more outputs from the second Splitter — pool first, divide second.', durationMs: 1500 },
      { action: { type: 'drawEdge', id: 'd-e9', source: 'd-s2', target: 'out-4', sourceHandle: 'out-1' },
        narration: '', durationMs: 700 },
    ],
    tryItPuzzle: {
      inputs: [
        { id: 'in-1', rate: 20, position: { x: 80, y: 120 } },
        { id: 'in-2', rate: 40, position: { x: 80, y: 220 } },
        { id: 'in-3', rate: 60, position: { x: 80, y: 320 } },
      ],
      outputs: [
        { id: 'out-1', targetRate: 30, position: { x: 600, y: 120 } },
        { id: 'out-2', targetRate: 30, position: { x: 600, y: 220 } },
        { id: 'out-3', targetRate: 30, position: { x: 600, y: 320 } },
        { id: 'out-4', targetRate: 30, position: { x: 600, y: 420 } },
      ],
      nodeBudget: { splitters: 2, mergers: 1 },
      solution: {
        nodes: [
          { id: 'sol-m1', type: 'mergerNode',   position: { x: 220, y: 220 } },
          { id: 'sol-s1', type: 'splitterNode', position: { x: 360, y: 220 } },
          { id: 'sol-s2', type: 'splitterNode', position: { x: 500, y: 320 } },
        ],
        edges: [
          { source: 'in-1', target: 'sol-m1', targetHandle: 'in-0' },
          { source: 'in-2', target: 'sol-m1', targetHandle: 'in-1' },
          { source: 'in-3', target: 'sol-m1', targetHandle: 'in-2' },
          { source: 'sol-m1', target: 'sol-s1', sourceHandle: 'out', targetHandle: 'in', mark: 2 },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0' },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1' },
          { source: 'sol-s1', target: 'sol-s2', sourceHandle: 'out-2', targetHandle: 'in' },
          { source: 'sol-s2', target: 'out-3', sourceHandle: 'out-0' },
          { source: 'sol-s2', target: 'out-4', sourceHandle: 'out-1' },
        ],
      },
    },
  },

  // ── 6. Belt speed as a tool ──────────────────────────────────────────────
  {
    id: 6,
    title: 'Belt speed as a tool',
    concept: 'Use belt capacity to bias an even split into uneven flows',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 280, y: 200 } },
        narration: '150/min in. Targets: 60 and 90. A naive 1:2 split gives 75 + 75 — wrong ratio.', durationMs: 2200 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-s1', targetHandle: 'in', mark: 3 },
        narration: 'Wire the input. The trunk carries 150 — Mk.3 (270 cap) handles that.', durationMs: 1700 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-s1', target: 'out-1', sourceHandle: 'out-0', mark: 1 },
        narration: 'Top edge: Mk.1 belt → caps the flow at 60/min.', durationMs: 1700 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'out-2', sourceHandle: 'out-1', mark: 2 },
        narration: 'Bottom edge: Mk.2 belt soaks up the residual 90/min.', durationMs: 2000 },
      { action: { type: 'pause' },
        narration: 'Belt tiers throttle individual edges, biasing the even split into uneven targets.', durationMs: 2200 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 150, position: { x: 80, y: 200 } }],
      outputs: [
        { id: 'out-1', targetRate: 60, position: { x: 500, y: 150 } },
        { id: 'out-2', targetRate: 90, position: { x: 500, y: 280 } },
      ],
      nodeBudget: { splitters: 1, mergers: 0 },
      solution: {
        nodes: [{ id: 'sol-s1', type: 'splitterNode', position: { x: 280, y: 200 } }],
        edges: [
          { source: 'in-1', target: 'sol-s1', targetHandle: 'in', mark: 3 },
          { source: 'sol-s1', target: 'out-1', sourceHandle: 'out-0', mark: 1 },
          { source: 'sol-s1', target: 'out-2', sourceHandle: 'out-1', mark: 2 },
        ],
      },
    },
  },

  // ── 7. Loopbacks ─────────────────────────────────────────────────────────
  {
    id: 7,
    title: 'Loopbacks',
    concept: 'Route excess belt back to build unbuildable ratios',
    demoSteps: [
      { action: { type: 'placeNode', nodeType: 'mergerNode', id: 'd-m1', position: { x: 200, y: 240 } },
        narration: '60/min in, five outputs at 12/min each. A direct 1:5 split is impossible — Splitters only divide by 2 or 3.', durationMs: 2400 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s1', position: { x: 320, y: 240 } },
        narration: 'Trunk Splitter divides the merged flow into two halves.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s2', position: { x: 440, y: 140 } },
        narration: 'Top branch: one half is split into thirds — three equal lanes.', durationMs: 1800 },
      { action: { type: 'placeNode', nodeType: 'splitterNode', id: 'd-s3', position: { x: 440, y: 340 } },
        narration: 'Bottom branch: the other half also into thirds. 2 × 3 = 6 equal lanes.', durationMs: 2000 },
      { action: { type: 'drawEdge', id: 'd-e1', source: 'in-1', target: 'd-m1', targetHandle: 'in-0' },
        narration: 'Input feeds the Merger.', durationMs: 1200 },
      { action: { type: 'drawEdge', id: 'd-e2', source: 'd-m1', target: 'd-s1', sourceHandle: 'out', targetHandle: 'in', mark: 2 },
        narration: 'Merger feeds the trunk Splitter — Mk.2 belt, since 60 + loopback exceeds 60/min.', durationMs: 1700 },
      { action: { type: 'drawEdge', id: 'd-e3', source: 'd-s1', target: 'd-s2', sourceHandle: 'out-0', targetHandle: 'in' },
        narration: 'Trunk halves go to the two branch Splitters.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e4', source: 'd-s1', target: 'd-s3', sourceHandle: 'out-1', targetHandle: 'in' },
        narration: '', durationMs: 700 },
      { action: { type: 'drawEdge', id: 'd-e5', source: 'd-s2', target: 'out-1', sourceHandle: 'out-0' },
        narration: 'Top branch — three lanes to three outputs.', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e6', source: 'd-s2', target: 'out-2', sourceHandle: 'out-1' },
        narration: '', durationMs: 600 },
      { action: { type: 'drawEdge', id: 'd-e7', source: 'd-s2', target: 'out-3', sourceHandle: 'out-2' },
        narration: '', durationMs: 600 },
      { action: { type: 'drawEdge', id: 'd-e8', source: 'd-s3', target: 'out-4', sourceHandle: 'out-0' },
        narration: 'Bottom branch — two lanes to the remaining outputs…', durationMs: 1300 },
      { action: { type: 'drawEdge', id: 'd-e9', source: 'd-s3', target: 'out-5', sourceHandle: 'out-1' },
        narration: '', durationMs: 600 },
      { action: { type: 'drawEdge', id: 'd-e10', source: 'd-s3', target: 'd-m1', sourceHandle: 'out-2', targetHandle: 'in-1' },
        narration: '…and the sixth lane loops back into the Merger. The system self-balances: 60 + 12 in, 12 × 6 split, 12 fed back. Five 12/min outputs.', durationMs: 2800 },
    ],
    tryItPuzzle: {
      inputs: [{ id: 'in-1', rate: 60, position: { x: 80, y: 240 } }],
      outputs: [
        { id: 'out-1', targetRate: 12, position: { x: 600, y: 80 } },
        { id: 'out-2', targetRate: 12, position: { x: 600, y: 160 } },
        { id: 'out-3', targetRate: 12, position: { x: 600, y: 240 } },
        { id: 'out-4', targetRate: 12, position: { x: 600, y: 320 } },
        { id: 'out-5', targetRate: 12, position: { x: 600, y: 400 } },
      ],
      nodeBudget: { splitters: 3, mergers: 1 },
      solution: {
        nodes: [
          { id: 'sol-m1', type: 'mergerNode',   position: { x: 200, y: 240 } },
          { id: 'sol-s1', type: 'splitterNode', position: { x: 320, y: 240 } },
          { id: 'sol-s2', type: 'splitterNode', position: { x: 440, y: 140 } },
          { id: 'sol-s3', type: 'splitterNode', position: { x: 440, y: 340 } },
        ],
        edges: [
          { source: 'in-1',   target: 'sol-m1', targetHandle: 'in-0' },
          { source: 'sol-m1', target: 'sol-s1', sourceHandle: 'out',   targetHandle: 'in', mark: 2 },
          { source: 'sol-s1', target: 'sol-s2', sourceHandle: 'out-0', targetHandle: 'in' },
          { source: 'sol-s1', target: 'sol-s3', sourceHandle: 'out-1', targetHandle: 'in' },
          { source: 'sol-s2', target: 'out-1',  sourceHandle: 'out-0' },
          { source: 'sol-s2', target: 'out-2',  sourceHandle: 'out-1' },
          { source: 'sol-s2', target: 'out-3',  sourceHandle: 'out-2' },
          { source: 'sol-s3', target: 'out-4',  sourceHandle: 'out-0' },
          { source: 'sol-s3', target: 'out-5',  sourceHandle: 'out-1' },
          { source: 'sol-s3', target: 'sol-m1', sourceHandle: 'out-2', targetHandle: 'in-1' },
        ],
      },
    },
  },
]
