// One-shot icon generator. Run with `node scripts/gen-icons.mjs`.
// Produces public/icon-192.png and public/icon-512.png — solid #020617
// background with an amber #f59e0b "BB" wordmark. PNGs are generated by
// hand using zlib so we don't need to install sharp/canvas as deps.
//
// The "BB" glyphs are drawn from a tiny 7x7 bitmap font, scaled by the
// per-icon scale factor.

import { writeFileSync } from 'node:fs'
import { deflateSync } from 'node:zlib'
import { Buffer } from 'node:buffer'
import { createHash } from 'node:crypto'

// ── Bitmap font (7 cols x 7 rows, '#' = filled) ─────────────────────────────
const GLYPH_B = [
  '######.',
  '#.....#',
  '#.....#',
  '######.',
  '#.....#',
  '#.....#',
  '######.',
]
const GLYPH_W = 7
const GLYPH_H = 7

// ── Colors ──────────────────────────────────────────────────────────────────
// #020617 background (RGB 2 6 23), #f59e0b foreground (RGB 245 158 11).
const BG = [0x02, 0x06, 0x17]
const FG = [0xf5, 0x9e, 0x0b]

function buildIcon(size) {
  // Layout: two glyphs separated by 1 glyph-cell of space, centered.
  // Total width in glyph cells = 7 + 1 + 7 = 15.
  const totalCells = GLYPH_W + 1 + GLYPH_W
  const scale = Math.floor(size * 0.62 / totalCells) // ~62% of icon width
  const wordW = totalCells * scale
  const wordH = GLYPH_H * scale
  const startX = Math.floor((size - wordW) / 2)
  const startY = Math.floor((size - wordH) / 2)

  // Pixel buffer: 3 bytes per pixel (RGB), filled with BG.
  const pixels = Buffer.alloc(size * size * 3)
  for (let i = 0; i < size * size; i++) {
    pixels[i * 3]     = BG[0]
    pixels[i * 3 + 1] = BG[1]
    pixels[i * 3 + 2] = BG[2]
  }

  function drawGlyph(glyph, originX, originY) {
    for (let gy = 0; gy < GLYPH_H; gy++) {
      const row = glyph[gy]
      for (let gx = 0; gx < GLYPH_W; gx++) {
        if (row[gx] !== '#') continue
        const px0 = originX + gx * scale
        const py0 = originY + gy * scale
        for (let dy = 0; dy < scale; dy++) {
          for (let dx = 0; dx < scale; dx++) {
            const x = px0 + dx
            const y = py0 + dy
            if (x < 0 || x >= size || y < 0 || y >= size) continue
            const idx = (y * size + x) * 3
            pixels[idx]     = FG[0]
            pixels[idx + 1] = FG[1]
            pixels[idx + 2] = FG[2]
          }
        }
      }
    }
  }

  drawGlyph(GLYPH_B, startX, startY)
  drawGlyph(GLYPH_B, startX + (GLYPH_W + 1) * scale, startY)

  return encodePng(size, size, pixels)
}

// ── Minimal PNG encoder ─────────────────────────────────────────────────────
function encodePng(width, height, rgb) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

  // IHDR
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8]  = 8       // bit depth
  ihdr[9]  = 2       // color type RGB
  ihdr[10] = 0       // compression
  ihdr[11] = 0       // filter
  ihdr[12] = 0       // interlace

  // Filtered scanlines: prepend 0x00 (filter: None) per row.
  const stride = width * 3
  const filtered = Buffer.alloc((stride + 1) * height)
  for (let y = 0; y < height; y++) {
    filtered[y * (stride + 1)] = 0
    rgb.copy(filtered, y * (stride + 1) + 1, y * stride, y * stride + stride)
  }
  const idatData = deflateSync(filtered)

  return Buffer.concat([
    sig,
    chunk('IHDR', ihdr),
    chunk('IDAT', idatData),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

function chunk(type, data) {
  const length = Buffer.alloc(4)
  length.writeUInt32BE(data.length, 0)
  const typeBuf = Buffer.from(type, 'ascii')
  const crc = crc32(Buffer.concat([typeBuf, data]))
  const crcBuf = Buffer.alloc(4)
  crcBuf.writeUInt32BE(crc >>> 0, 0)
  return Buffer.concat([length, typeBuf, data, crcBuf])
}

// CRC32 table
const CRC_TABLE = new Uint32Array(256)
for (let n = 0; n < 256; n++) {
  let c = n
  for (let k = 0; k < 8; k++) {
    c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1)
  }
  CRC_TABLE[n] = c >>> 0
}
function crc32(buf) {
  let c = 0xffffffff
  for (let i = 0; i < buf.length; i++) {
    c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8)
  }
  return (c ^ 0xffffffff) >>> 0
}

// ── Run ─────────────────────────────────────────────────────────────────────
const png192 = buildIcon(192)
const png512 = buildIcon(512)
writeFileSync(new URL('../public/icon-192.png', import.meta.url), png192)
writeFileSync(new URL('../public/icon-512.png', import.meta.url), png512)
console.log('icon-192.png', png192.length, 'sha1', createHash('sha1').update(png192).digest('hex'))
console.log('icon-512.png', png512.length, 'sha1', createHash('sha1').update(png512).digest('hex'))
